// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Buffer$AgdaModeVscode = require("./Buffer.bs.js");

function make(param) {
  return {
          activated: false,
          buffer: Buffer$AgdaModeVscode.make(undefined),
          textBeforeActivation: ""
        };
}

function activate(self, text) {
  self.activated = true;
  self.textBeforeActivation = text;
  
}

function deactivate(self) {
  self.activated = false;
  self.buffer = Buffer$AgdaModeVscode.make(undefined);
  self.textBeforeActivation = "";
  
}

function init(s) {
  return s.substring(0, s.length - 1 | 0);
}

function last(s) {
  return s.substring(s.length - 1 | 0);
}

function deviseChange(self, input) {
  var inputLength = input.length;
  var bufferSurface = Buffer$AgdaModeVscode.toSurface(self.buffer);
  if (init(input) === self.textBeforeActivation + bufferSurface) {
    return {
            offset: inputLength - 1 | 0,
            insertedText: last(input),
            replacedTextLength: 0
          };
  } else if (input === self.textBeforeActivation || input === self.textBeforeActivation + init(bufferSurface)) {
    return {
            offset: inputLength,
            insertedText: "",
            replacedTextLength: 1
          };
  } else {
    return ;
  }
}

function update(self, input) {
  var change = deviseChange(self, input);
  if (change !== undefined) {
    var match = Buffer$AgdaModeVscode.update(self.buffer, self.textBeforeActivation.length, change);
    var shouldRewrite = match[1];
    var buffer = match[0];
    if (buffer.translation.further) {
      self.buffer = buffer;
      return [
              self.textBeforeActivation + Buffer$AgdaModeVscode.toSurface(buffer),
              {
                TAG: 1,
                _0: Buffer$AgdaModeVscode.toSequence(buffer),
                _1: buffer.translation,
                _2: buffer.candidateIndex,
                [Symbol.for("name")]: "Update"
              }
            ];
    } else {
      self.buffer = Buffer$AgdaModeVscode.make(undefined);
      self.activated = false;
      if (shouldRewrite !== undefined) {
        return [
                self.textBeforeActivation + shouldRewrite,
                /* Deactivate */1
              ];
      } else {
        return [
                input,
                /* Deactivate */1
              ];
      }
    }
  }
  deactivate(self);
  
}

function insertChar(self, $$char) {
  return update(self, self.textBeforeActivation + (Buffer$AgdaModeVscode.toSurface(self.buffer) + $$char));
}

exports.make = make;
exports.activate = activate;
exports.deactivate = deactivate;
exports.init = init;
exports.last = last;
exports.deviseChange = deviseChange;
exports.update = update;
exports.insertChar = insertChar;
/* Buffer-AgdaModeVscode Not a pure module */
