// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Main$AgdaModeVscode = require("./Main.bs.js");
var Connection__Download$AgdaModeVscode = require("../Connection/Download/Connection__Download.bs.js");
var Connection__Download__Trace$AgdaModeVscode = require("../Connection/Download/Connection__Download__Trace.bs.js");
var Connection__Download__Source$AgdaModeVscode = require("../Connection/Download/Connection__Download__Source.bs.js");
var Connection__Download__ManagedStorage$AgdaModeVscode = require("../Connection/Download/Connection__Download__ManagedStorage.bs.js");

function determinePlatform() {
  return Promise.resolve({
              TAG: "Ok",
              _0: "Web"
            });
}

function findCommand(_command, _timeoutOpt) {
  return Promise.resolve({
              TAG: "Error",
              _0: "NotFound"
            });
}

async function alreadyDownloaded(globalStorageUri) {
  return await Connection__Download__ManagedStorage$AgdaModeVscode.findAnyWasmDownloaded(globalStorageUri);
}

function resolveDownloadChannel(channel, _useCache) {
  return async function (param, param$1, param$2) {
    if (channel === "LatestALS") {
      return {
              TAG: "Error",
              _0: "CannotFindCompatibleALSRelease"
            };
    } else {
      return {
              TAG: "Ok",
              _0: Connection__Download__Source$AgdaModeVscode.hardcodedALSWasmFromNPM
            };
    }
  };
}

function download(globalStorageUri, channel, traceOpt) {
  var trace = traceOpt !== undefined ? traceOpt : Connection__Download__Trace$AgdaModeVscode.noop;
  return Connection__Download$AgdaModeVscode.download(globalStorageUri, channel, trace, undefined, undefined);
}

function askUserAboutDownloadPolicy() {
  return Promise.resolve("Yes");
}

var Web = {
  determinePlatform: determinePlatform,
  findCommand: findCommand,
  alreadyDownloaded: alreadyDownloaded,
  resolveDownloadChannel: resolveDownloadChannel,
  download: download,
  askUserAboutDownloadPolicy: askUserAboutDownloadPolicy
};

function make() {
  return Web;
}

function activate(context) {
  return Main$AgdaModeVscode.activate(Web, context);
}

var deactivate = Main$AgdaModeVscode.deactivate;

exports.Web = Web;
exports.make = make;
exports.activate = activate;
exports.deactivate = deactivate;
/* Main-AgdaModeVscode Not a pure module */
