// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Connection__Resolver__TCP$AgdaModeVscode = require("./Resolver/Connection__Resolver__TCP.bs.js");
var Connection__Resolver__GitHub$AgdaModeVscode = require("./Resolver/Connection__Resolver__GitHub.bs.js");
var Connection__Resolver__Command$AgdaModeVscode = require("./Resolver/Connection__Resolver__Command.bs.js");

function toString(error) {
  switch (error.TAG) {
    case "File" :
        return "Trying to locate \"" + error._0 + "\" but the file does not exist";
    case "Command" :
        return "Trying to find the command \"" + error._0 + "\": " + Connection__Resolver__Command$AgdaModeVscode.$$Error.toString(error._1);
    case "TCP" :
        return "Trying to connect to " + error._0.toString() + " but got " + Connection__Resolver__TCP$AgdaModeVscode.$$Error.toString(error._1);
    case "GitHub" :
        return "Trying to download prebuilt from GitHub: " + Connection__Resolver__GitHub$AgdaModeVscode.$$Error.toString(error._0);
    
  }
}

var $$Error = {
  toString: toString
};

var Module = {};

var Command;

var $$File;

var TCP;

var GitHub;

var IPC;

exports.Command = Command;
exports.$$File = $$File;
exports.TCP = TCP;
exports.GitHub = GitHub;
exports.IPC = IPC;
exports.$$Error = $$Error;
exports.Module = Module;
/* Connection__Resolver__TCP-AgdaModeVscode Not a pure module */
