// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Nodeurl = require("node:url");
var Nodepath = require("node:path");
var Untildify = require("untildify");
var OS$AgdaModeVscode = require("../../Util/OS.bs.js");

function parse(path) {
  var result;
  try {
    result = new Nodeurl.URL(path);
  }
  catch (exn){
    result = undefined;
  }
  var result$1 = result !== undefined && result.protocol === "lsp:" ? result : undefined;
  if (result$1 !== undefined) {
    return {
            TAG: "URL",
            _0: result$1
          };
  }
  var path$1 = Untildify(path);
  var path$2 = Nodepath.normalize(path$1);
  var path$3 = OS$AgdaModeVscode.onUnix ? path$2 : path$2.replace(/^\\([a-zA-Z])\\/, "$1\:\\");
  return {
          TAG: "Filepath",
          _0: path$3
        };
}

function toString(path) {
  if (path.TAG === "Filepath") {
    return Nodepath.normalize(path._0);
  } else {
    return path._0.toString();
  }
}

function equal(x, y) {
  if (x.TAG === "Filepath") {
    if (y.TAG === "Filepath") {
      return x._0 === y._0;
    } else {
      return false;
    }
  } else if (y.TAG === "Filepath") {
    return false;
  } else {
    return x._0.toString() === y._0.toString();
  }
}

exports.parse = parse;
exports.toString = toString;
exports.equal = equal;
/* node:url Not a pure module */
