// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Vscode = require("vscode");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Core__Array = require("@rescript/core/lib/js/src/Core__Array.bs.js");
var FS$AgdaModeVscode = require("../../FS.bs.js");
var Util$AgdaModeVscode = require("../../Util/Util.bs.js");
var Config$AgdaModeVscode = require("../../Config.bs.js");
var Memento$AgdaModeVscode = require("../../Memento.bs.js");
var Connection__Download$AgdaModeVscode = require("./Connection__Download.bs.js");
var Connection__Candidate$AgdaModeVscode = require("../Connection__Candidate.bs.js");

async function run(memento, globalStorageUri, logChannel) {
  var cleanedDirectories = {
    contents: []
  };
  var failedUris = {
    contents: []
  };
  var deleteRoot = async function (uri) {
    Util$AgdaModeVscode.log("[ debug ] delete downloads: deleting managed directory", uri.toString());
    var error = await FS$AgdaModeVscode.deleteRecursive(uri);
    if (error.TAG === "Ok") {
      Util$AgdaModeVscode.log("[ debug ] delete downloads: deleted managed directory", uri.toString());
      cleanedDirectories.contents = cleanedDirectories.contents.concat([uri]);
      return ;
    }
    Util$AgdaModeVscode.log("[ debug ] delete downloads: deleteRecursive failed", uri.toString() + ": " + error._0);
    var match = await FS$AgdaModeVscode.stat(uri);
    if (match.TAG === "Ok") {
      Util$AgdaModeVscode.log("[ debug ] delete downloads: directory still exists after failed delete", uri.toString());
      failedUris.contents = failedUris.contents.concat([uri]);
      return ;
    }
    Util$AgdaModeVscode.log("[ debug ] delete downloads: directory already missing, treating as cleaned", uri.toString());
    cleanedDirectories.contents = cleanedDirectories.contents.concat([uri]);
  };
  var managedRoots = Connection__Download$AgdaModeVscode.managedDeleteRoots(globalStorageUri);
  Util$AgdaModeVscode.log("[ debug ] delete downloads: globalStorageUri", globalStorageUri.toString());
  Util$AgdaModeVscode.log("[ debug ] delete downloads: managed roots", managedRoots.map(function (root) {
              return root.toString();
            }).join(" | "));
  var deleteAllRoots = async function (index) {
    if (index < managedRoots.length) {
      await deleteRoot(Belt_Array.getExn(managedRoots, index));
      return await deleteAllRoots(index + 1 | 0);
    }
    
  };
  await deleteAllRoots(0);
  var inFlightUri = Vscode.Uri.joinPath(globalStorageUri, "in-flight.download");
  var inFlightZipUri = Vscode.Uri.joinPath(globalStorageUri, "in-flight.download.zip");
  await FS$AgdaModeVscode.$$delete(inFlightUri);
  await FS$AgdaModeVscode.$$delete(inFlightZipUri);
  await Memento$AgdaModeVscode.Module.ALSReleaseCache.clear(memento, "agda", "agda-language-server");
  await Memento$AgdaModeVscode.Module.ALSReleaseCache.clear(memento, "banacorn", "agda-language-server");
  Util$AgdaModeVscode.log("[ debug ] delete downloads: cleaned directories", cleanedDirectories.contents.map(function (dir) {
              return dir.toString();
            }).join(" | "));
  Util$AgdaModeVscode.log("[ debug ] delete downloads: failed uris", failedUris.contents.map(function (uri) {
              return uri.toString();
            }).join(", "));
  await Memento$AgdaModeVscode.Module.ResolvedMetadata.clearUnderDirectories(memento, cleanedDirectories.contents);
  var currentPaths = Config$AgdaModeVscode.Connection.getAgdaPaths();
  Util$AgdaModeVscode.log("[ debug ] delete downloads: current connection.paths", currentPaths.join(" | "));
  var filteredPaths = currentPaths.filter(function (candidate) {
        var matchedDirectory = Core__Array.reduce(cleanedDirectories.contents, undefined, (function (found, dirUri) {
                if (found !== undefined) {
                  return found;
                } else if (Connection__Candidate$AgdaModeVscode.isUnderDirectory(Connection__Candidate$AgdaModeVscode.make(candidate), dirUri)) {
                  return Caml_option.some(dirUri);
                } else {
                  return ;
                }
              }));
        if (matchedDirectory !== undefined) {
          Util$AgdaModeVscode.log("[ debug ] delete downloads: removing connection.path candidate", candidate + " under " + Caml_option.valFromOption(matchedDirectory).toString());
          return false;
        } else {
          Util$AgdaModeVscode.log("[ debug ] delete downloads: preserving connection.path candidate", candidate);
          return true;
        }
      });
  Util$AgdaModeVscode.log("[ debug ] delete downloads: filtered connection.paths", filteredPaths.join(" | "));
  await Config$AgdaModeVscode.Connection.setAgdaPaths(logChannel, filteredPaths);
  return {
          cleanedDirectories: cleanedDirectories.contents,
          failedUris: failedUris.contents
        };
}

exports.run = run;
/* vscode Not a pure module */
