// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Body(Props) {
  var body = Props.body;
  if (body !== undefined) {
    return React.createElement("div", {
                className: "agda-mode-body"
              }, body);
  } else {
    return React.createElement(React.Fragment, undefined);
  }
}

var make = Body;

exports.make = make;
/* react Not a pure module */
