// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Caml_primitive = require("bs-platform/lib/js/caml_primitive.js");

function reducer(totalSize, index, action) {
  switch (action) {
    case /* Up */0 :
        return Caml_primitive.caml_int_max(0, index - 10 | 0);
    case /* Down */1 :
        return Caml_primitive.caml_int_min(totalSize - 1 | 0, index + 10 | 0);
    case /* Right */2 :
        return Caml_primitive.caml_int_min(totalSize - 1 | 0, index + 1 | 0);
    case /* Left */3 :
        return Caml_primitive.caml_int_max(0, index - 1 | 0);
    
  }
}

function CandidateSymbols(Props) {
  var candidates = Props.candidates;
  var partial_arg = candidates.length;
  var match = React.useReducer((function (param, param$1) {
          return reducer(partial_arg, param, param$1);
        }), 0);
  var index = match[0];
  var rowStart = Caml_int32.imul(index / 10 | 0, 10);
  var row = Belt_Array.slice(candidates, rowStart, 10);
  var match$1 = Belt_Array.get(candidates, index);
  return React.createElement("div", {
              className: "agda-mode-keyboard-candidates"
            }, match$1 !== undefined ? Belt_Array.mapWithIndex(row, (function (i, key) {
                      var isSelected = (rowStart + i | 0) === index;
                      return React.createElement("button", {
                                  key: key,
                                  className: "agda-mode-key " + (
                                    isSelected ? "selected" : ""
                                  ),
                                  onClick: (function (param) {
                                      console.log(key);
                                      
                                    })
                                }, key);
                    })) : React.createElement(React.Fragment, undefined));
}

var make = CandidateSymbols;

exports.reducer = reducer;
exports.make = make;
/* react Not a pure module */
