// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Keyboard(Props) {
  var activated = Props.activated;
  var activated$1 = activated ? " activated" : " deactivated";
  return React.createElement("div", {
              className: "agda-mode-keyboard" + activated$1
            }, "deactivated");
}

var make = Keyboard;

exports.make = make;
/* react Not a pure module */
