// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Nodeos = require("node:os");

var match = Nodeos.type();

var onUnix = match === "Windows_NT" ? false : true;

exports.onUnix = onUnix;
/* match Not a pure module */
