// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Vscode = require("vscode");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Core__Dict = require("@rescript/core/lib/js/src/Core__Dict.bs.js");
var Editor$AgdaModeVscode = require("../Editor.bs.js");

function toDecorations(input) {
  var backgroundColorDict = {};
  var foregroundColorDict = {};
  var backgroundUnderlinedColorDict = {};
  var foregroundUnderlinedColorDict = {};
  var addToDict = function (dict, color, range) {
    var ranges = dict[color];
    if (ranges !== undefined) {
      ranges.push(range);
    } else {
      dict[color] = [range];
    }
  };
  var addFaceToDict = function (face, range) {
    switch (face.TAG) {
      case "Background" :
          return addToDict(backgroundColorDict, face._0, range);
      case "Foreground" :
          return addToDict(foregroundColorDict, face._0, range);
      case "BackgroundUnderlined" :
          return addToDict(backgroundUnderlinedColorDict, face._0, range);
      case "ForegroundUnderlined" :
          return addToDict(foregroundUnderlinedColorDict, face._0, range);
      
    }
  };
  input.forEach(function (param) {
        var range = param[1];
        var match = param[0];
        var theme = Vscode.window.activeColorTheme.kind;
        if (theme === 2) {
          return addFaceToDict(match.dark, range);
        } else {
          return addFaceToDict(match.light, range);
        }
      });
  var resultDict = new Map();
  Core__Dict.forEachWithKey(backgroundColorDict, (function (ranges, color) {
          var decoration = Editor$AgdaModeVscode.Decoration.createBackgroundWithColor(undefined, color);
          var existingRanges = resultDict.get(decoration);
          if (existingRanges !== undefined) {
            resultDict.set(decoration, Belt_Array.concatMany([
                      existingRanges,
                      ranges
                    ]));
          } else {
            resultDict.set(decoration, ranges);
          }
        }));
  Core__Dict.forEachWithKey(foregroundColorDict, (function (ranges, color) {
          var decoration = Editor$AgdaModeVscode.Decoration.createTextWithColor(undefined, color);
          var existingRanges = resultDict.get(decoration);
          if (existingRanges !== undefined) {
            resultDict.set(decoration, Belt_Array.concatMany([
                      existingRanges,
                      ranges
                    ]));
          } else {
            resultDict.set(decoration, ranges);
          }
        }));
  Core__Dict.forEachWithKey(backgroundUnderlinedColorDict, (function (ranges, color) {
          var decoration = Editor$AgdaModeVscode.Decoration.createBackgroundWithColor(true, color);
          var existingRanges = resultDict.get(decoration);
          if (existingRanges !== undefined) {
            resultDict.set(decoration, Belt_Array.concatMany([
                      existingRanges,
                      ranges
                    ]));
          } else {
            resultDict.set(decoration, ranges);
          }
        }));
  Core__Dict.forEachWithKey(foregroundUnderlinedColorDict, (function (ranges, color) {
          var decoration = Editor$AgdaModeVscode.Decoration.createTextWithColor(true, color);
          var existingRanges = resultDict.get(decoration);
          if (existingRanges !== undefined) {
            resultDict.set(decoration, Belt_Array.concatMany([
                      existingRanges,
                      ranges
                    ]));
          } else {
            resultDict.set(decoration, ranges);
          }
        }));
  return resultDict;
}

function toDecoration(self) {
  var convert = function (color) {
    switch (color.TAG) {
      case "Background" :
          return Editor$AgdaModeVscode.Decoration.createBackgroundWithColor(undefined, color._0);
      case "Foreground" :
          return Editor$AgdaModeVscode.Decoration.createTextWithColor(undefined, color._0);
      case "BackgroundUnderlined" :
          return Editor$AgdaModeVscode.Decoration.createBackgroundWithColor(true, color._0);
      case "ForegroundUnderlined" :
          return Editor$AgdaModeVscode.Decoration.createTextWithColor(true, color._0);
      
    }
  };
  var theme = Vscode.window.activeColorTheme.kind;
  if (theme === 2) {
    return convert(self.dark);
  } else {
    return convert(self.light);
  }
}

exports.toDecorations = toDecorations;
exports.toDecoration = toDecoration;
/* vscode Not a pure module */
