// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Decoration;

var SemanticToken;

var Agda;

exports.Decoration = Decoration;
exports.SemanticToken = SemanticToken;
exports.Agda = Agda;
/* No side effect */
