include Connection__Core

let activateSwitchVersion = Connection__Switch.activate
let switchCandidate = Connection__Switch.switchAgdaVersion
let getAvailableSwitchDownloads = Connection__Switch.getAvailableDownloads
