// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Connection$AgdaModeVscode = require("../../src/Connection/Connection.bs.js");
var Test__Util$AgdaModeVscode = require("./Test__Util.bs.js");
var Connection__Error$AgdaModeVscode = require("../../src/Connection/Connection__Error.bs.js");

describe.skip("Connection", (function () {
        Test__Util$AgdaModeVscode.Q.it("should download the language server", (async function () {
                var globalStoragePath = Test__Util$AgdaModeVscode.Path.globalStoragePath;
                var e = await Connection$AgdaModeVscode.start(globalStoragePath, true, (function (param) {
                        
                      }));
                if (e.TAG === "Ok") {
                  return {
                          TAG: "Ok",
                          _0: undefined,
                          [Symbol.for("name")]: "Ok"
                        };
                }
                var match = Connection__Error$AgdaModeVscode.toString(e._0);
                var message = match[0] + "\n" + match[1];
                return await Test__Util$AgdaModeVscode.A.fail(message);
              }));
      }));

/*  Not a pure module */
