// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Assert = require("assert");
var Vscode = require("vscode");
var Nodepath = require("node:path");
var FS$AgdaModeVscode = require("../../src/FS.bs.js");
var Goals$AgdaModeVscode = require("../../src/Goals.bs.js");
var Registry$AgdaModeVscode = require("../../src/Registry.bs.js");
var Test__Util$AgdaModeVscode = require("./Test__Util.bs.js");

describe("issue #316 cached .agdai with --allow-unsolved-metas", (function () {
        this.timeout(20000);
        var fixtureDir = Test__Util$AgdaModeVscode.Path.asset("Issue316");
        var buildUri = Vscode.Uri.file(Nodepath.join(fixtureDir, "_build"));
        var runCachedBuild = function (cwd) {
          ((function(cwd) {
      require("node:child_process").execFileSync("agda", ["Main.agda"], {
        cwd,
        stdio: "pipe",
      });
      return;
    })(cwd));
        };
        beforeEach(async function () {
              await FS$AgdaModeVscode.deleteRecursive(buildUri);
            });
        afterEach(async function () {
              await FS$AgdaModeVscode.deleteRecursive(buildUri);
              return await Registry$AgdaModeVscode.removeAndDestroyAll();
            });
        it("should still expose holes after loading CacheHole.agda", (async function () {
                runCachedBuild(fixtureDir);
                var ctx = await Test__Util$AgdaModeVscode.AgdaMode.makeAndLoad("Issue316/CacheHole.agda");
                try {
                  var goals = Goals$AgdaModeVscode.serializeGoals(ctx.state.goals);
                  if (goals.length !== 2) {
                    Assert.fail("expected 2 goals after load even when .agdai was cached from --allow-unsolved-metas, got " + String(goals.length));
                  }
                  return await Test__Util$AgdaModeVscode.AgdaMode.quit(ctx);
                }
                catch (exn){
                  await Test__Util$AgdaModeVscode.AgdaMode.quit(ctx);
                  throw exn;
                }
              }));
      }));

/*  Not a pure module */
