// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Config$AgdaModeVscode = require("../../src/Config.bs.js");

describe("agda-mode.compile", (function () {
        var savedBackend = {
          contents: Config$AgdaModeVscode.backendInTestingMode.contents
        };
        beforeEach(async function () {
              savedBackend.contents = Config$AgdaModeVscode.backendInTestingMode.contents;
            });
        afterEach(async function () {
              Config$AgdaModeVscode.backendInTestingMode.contents = savedBackend.contents;
            });
      }));

/*  Not a pure module */
