// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml = require("rescript/lib/js/caml.js");
var Curry = require("rescript/lib/js/curry.js");
var Assert = require("assert");
var Vscode = require("vscode");
var Nodepath = require("node:path");
var Core__Array = require("@rescript/core/lib/js/src/Core__Array.bs.js");
var Core__Option = require("@rescript/core/lib/js/src/Core__Option.bs.js");
var Caml_js_exceptions = require("rescript/lib/js/caml_js_exceptions.js");
var Log$AgdaModeVscode = require("../../src/State/Log.bs.js");
var Chan$AgdaModeVscode = require("../../src/Util/Chan.bs.js");
var Util$AgdaModeVscode = require("../../src/Util/Util.bs.js");
var Test__Util$AgdaModeVscode = require("./Test__Util.bs.js");
var Connection__Error$AgdaModeVscode = require("../../src/Connection/Shared/Connection__Error.bs.js");
var Test__EditorLayout__Util$AgdaModeVscode = require("./Test__EditorLayout__Util.bs.js");

function leaves(tree) {
  if (tree.TAG === "Group") {
    return [tree._0];
  } else {
    return tree._1.flatMap(function (child) {
                return leaves(child.tree);
              });
  }
}

function mapLeaves(tree, f) {
  if (tree.TAG === "Group") {
    return {
            TAG: "Group",
            _0: f(tree._0)
          };
  } else {
    return {
            TAG: "Split",
            _0: tree._0,
            _1: tree._1.map(function (child) {
                  return {
                          size: child.size,
                          tree: mapLeaves(child.tree, f)
                        };
                })
          };
  }
}

function round2(x) {
  return Math.round(x * 100.0) / 100.0;
}

function normalize(tree) {
  if (tree.TAG === "Group") {
    return tree;
  }
  var children = tree._1;
  var total = Core__Array.reduce(children, 0.0, (function (acc, child) {
          return acc + child.size;
        }));
  return {
          TAG: "Split",
          _0: tree._0,
          _1: children.map(function (child) {
                return {
                        size: round2(child.size / total),
                        tree: normalize(child.tree)
                      };
              })
        };
}

function flip(orientation) {
  if (orientation === "LeftRight") {
    return "TopBottom";
  } else {
    return "LeftRight";
  }
}

function orientationOfInt(n) {
  if (n === 0) {
    return "LeftRight";
  } else {
    return "TopBottom";
  }
}

function intOfOrientation(orientation) {
  if (orientation === "LeftRight") {
    return 0;
  } else {
    return 1;
  }
}

function parseLayout(raw) {
  var counter = {
    contents: 0
  };
  var go = function (orientation, groups) {
    return {
            TAG: "Split",
            _0: orientation,
            _1: groups.map(function (group) {
                  var children = group.groups;
                  var tree;
                  var exit = 0;
                  if (children !== undefined && children.length > 0) {
                    tree = go(flip(orientation), children);
                  } else {
                    exit = 1;
                  }
                  if (exit === 1) {
                    counter.contents = counter.contents + 1 | 0;
                    tree = {
                      TAG: "Group",
                      _0: counter.contents
                    };
                  }
                  return {
                          size: Core__Option.getOr(group.size, 1.0),
                          tree: tree
                        };
                })
          };
  };
  return go(orientationOfInt(raw.orientation), raw.groups);
}

function toRawGroup(sized) {
  var match = sized.tree;
  if (match.TAG === "Group") {
    return {
            size: sized.size
          };
  } else {
    return {
            groups: match._1.map(toRawGroup),
            size: sized.size
          };
  }
}

function toRawLayout(tree) {
  if (tree.TAG === "Group") {
    return {
            orientation: 0,
            groups: [{
                size: 1.0
              }]
          };
  } else {
    return {
            orientation: intOfOrientation(tree._0),
            groups: tree._1.map(toRawGroup)
          };
  }
}

var snapshotTabGroups = (function() {
  const vscode = require("vscode");
  return vscode.window.tabGroups.all.map(group => ({
    viewColumn: group.viewColumn,
    isActive: group.isActive,
    tabs: group.tabs.map(tab => ({
      kind: tab.input instanceof vscode.TabInputWebview
        ? "webview"
        : tab.input instanceof vscode.TabInputText
          ? "text"
          : "other",
      label: tab.label,
    })),
  }));
});

function nameOfGroup(group) {
  var tabs = group.tabs;
  if (tabs.length !== 0) {
    return tabs.map(function (tab) {
                  return tab.label.replace(".agda", "");
                }).join("+");
  } else {
    return "Empty";
  }
}

async function capture() {
  var raw = await Vscode.commands.executeCommand("vscode.getEditorLayout");
  var groups = snapshotTabGroups().toSorted(function (a, b) {
        return Caml.int_compare(a.viewColumn, b.viewColumn);
      });
  var indexed = parseLayout(raw);
  if (leaves(indexed).length !== groups.length) {
    throw {
          RE_EXN_ID: "Failure",
          _1: "the layout has " + leaves(indexed).length.toString() + " groups but window.tabGroups has " + groups.length.toString(),
          Error: new Error()
        };
  }
  var layout = mapLeaves(indexed, (function (index) {
          var group = groups[index - 1 | 0];
          if (group !== undefined) {
            return nameOfGroup(group);
          }
          throw {
                RE_EXN_ID: "Failure",
                _1: "no tab group for leaf " + index.toString(),
                Error: new Error()
              };
        }));
  return {
          layout: normalize(layout),
          activeGroup: Core__Option.mapOr(groups.find(function (group) {
                    return group.isActive;
                  }), "", nameOfGroup),
          activeEditor: Core__Option.map(Vscode.window.activeTextEditor, (function (editor) {
                  return Nodepath.basename(editor.document.fileName);
                }))
        };
}

var make = (function() {
    const vscode = require("vscode");
    const commands = vscode.commands;
    const original = commands.executeCommand;
    const layoutCalls = [];
    let panelOpened = false;
    let announcePanelOpened;
    const panelOpenedPromise = new Promise(resolve => { announcePanelOpened = resolve; });

    commands.executeCommand = function(id, ...args) {
      const result = original.call(commands, id, ...args);
      if (id === "vscode.setEditorLayout" || id === "vscode.getEditorLayout") {
        layoutCalls.push(Promise.resolve(result));
      }
      return result;
    };

    const subscription = vscode.window.tabGroups.onDidChangeTabs(event => {
      const opened = event.opened.some(tab =>
        tab.input instanceof vscode.TabInputWebview && tab.label === "Agda");
      if (opened) {
        panelOpened = true;
        announcePanelOpened();
      }
    });

    return {
      // Resolves once every recorded layout call has resolved, including the
      // ones made after an earlier one resolved, and, if asked to, the Agda
      // tab has opened. The timeout only guards against a hang; it never
      // decides that the layout is ready.
      settled: function(timeoutMs, waitForPanel) {
        const work = (async () => {
          if (waitForPanel) {
            await panelOpenedPromise;
          }
          let seen = 0;
          while (seen < layoutCalls.length) {
            const batch = layoutCalls.slice(seen);
            seen = layoutCalls.length;
            await Promise.all(batch);
          }
        })();
        let timer;
        const guard = new Promise((_, reject) => {
          timer = setTimeout(() => reject(new Error(
            "the layout did not settle within " + timeoutMs + "ms (Agda tab opened: " +
            panelOpened + ", layout calls: " + layoutCalls.length + ")")), timeoutMs);
        });
        return Promise.race([work, guard]).finally(() => clearTimeout(timer));
      },
      stop: function() {
        commands.executeCommand = original;
        subscription.dispose();
      },
    };
  });

var Observer = {
  make: make
};

var panelClosed = (function(timeoutMs) {
  const vscode = require("vscode");
  const exists = () => vscode.window.tabGroups.all.some(group =>
    group.tabs.some(tab =>
      tab.input instanceof vscode.TabInputWebview && tab.label === "Agda"));
  if (!exists()) {
    return Promise.resolve();
  }
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      subscription.dispose();
      const tabs = vscode.window.tabGroups.all.map(group => ({
        column: group.viewColumn,
        tabs: group.tabs.map(tab => ({
          label: tab.label,
          input: tab.input && tab.input.constructor ? tab.input.constructor.name : typeof tab.input,
        })),
      }));
      reject(new Error("the Agda panel tab did not close within " + timeoutMs + "ms; tabs: " + JSON.stringify(tabs)));
    }, timeoutMs);
    const subscription = vscode.window.tabGroups.onDidChangeTabs(() => {
      if (!exists()) {
        clearTimeout(timer);
        subscription.dispose();
        resolve();
      }
    });
  });
});

function stringSetting(section, key, value) {
  return {
          section: section,
          key: key,
          value: value
        };
}

function boolSetting(section, key, value) {
  return {
          section: section,
          key: key,
          value: value
        };
}

var updateGlobalSetting = (async function(section, key, value) {
    const vscode = require("vscode");
    const configuration = vscode.workspace.getConfiguration(section);
    const inspected = configuration.inspect(key);
    const previous = inspected ? inspected.globalValue : undefined;
    await configuration.update(key, value, vscode.ConfigurationTarget.Global);
    return previous;
  });

var showInColumn = (async function(path, column) {
    const vscode = require("vscode");
    await vscode.window.showTextDocument(vscode.Uri.file(path), {
      viewColumn: column,
      preview: false,
      preserveFocus: false,
    });
  });

var describeExn = (function(e) {
  return (e && e._1 && e._1.message) || (e && e.message) || String(e);
});

function positionName(position) {
  if (position === "Bottom") {
    return "bottom";
  } else {
    return "right";
  }
}

function fileOf(name) {
  return Test__Util$AgdaModeVscode.Path.asset(name + ".agda");
}

async function resetLayout() {
  await Vscode.commands.executeCommand("workbench.action.closeAllEditors");
  await Vscode.commands.executeCommand("vscode.setEditorLayout", {
        orientation: 0,
        groups: [{
            size: 1.0
          }]
      });
}

function withHangGuard(what, promise) {
  var guard = new Promise((function (param, reject) {
          setTimeout((function () {
                  reject({
                        RE_EXN_ID: "Failure",
                        _1: "timed out waiting for " + what
                      });
                }), 20000);
        }));
  return Promise.race([
              promise,
              guard
            ]);
}

function isDestructionComplete(log) {
  if (log.TAG === "Others" && log._0 === "State.destroy: Connection released, destruction complete") {
    return true;
  } else {
    return false;
  }
}

var loadedFiles = {
  contents: []
};

async function quit(channels, filepath) {
  await Test__Util$AgdaModeVscode.$$File.open_(filepath);
  var destroyCompleted = Log$AgdaModeVscode.on(channels.log, isDestructionComplete);
  var match = await Vscode.commands.executeCommand("agda-mode.quit");
  if (match !== undefined && match.TAG !== "Ok") {
    var match$1 = Connection__Error$AgdaModeVscode.toString(match._0);
    throw {
          RE_EXN_ID: "Failure",
          _1: match$1[0] + "\n" + match$1[1],
          Error: new Error()
        };
  }
  return await withHangGuard(filepath + " to be destroyed", destroyCompleted);
}

var closePanelTabs = (async function() {
  const vscode = require("vscode");
  const tabs = vscode.window.tabGroups.all.flatMap(group =>
    group.tabs.filter(tab =>
      tab.input instanceof vscode.TabInputWebview && tab.label === "Agda"));
  if (tabs.length > 0) {
    await vscode.window.tabGroups.close(tabs);
  }
});

async function reset(channels) {
  var files = loadedFiles.contents;
  loadedFiles.contents = [];
  var unique = files.filter(function (file, index) {
        return files.indexOf(file) === index;
      });
  for(var index = 0 ,index_finish = unique.length; index < index_finish; ++index){
    var file = unique[index];
    if (file !== undefined) {
      await quit(channels, file);
    }
    
  }
  await closePanelTabs();
  await panelClosed(20000);
  return await resetLayout();
}

async function clearWorkbench() {
  await Vscode.commands.executeCommand("workbench.action.closeSidebar");
  await Vscode.commands.executeCommand("workbench.action.closePanel");
  await Vscode.commands.executeCommand("workbench.action.closeAuxiliaryBar");
}

async function measureEditorWidth() {
  await Vscode.commands.executeCommand("vscode.setEditorLayout", {
        orientation: 0,
        groups: [
          {
            size: 1.0
          },
          {
            size: 1.0
          }
        ]
      });
  var raw = await Vscode.commands.executeCommand("vscode.getEditorLayout");
  return Core__Array.reduce(raw.groups, 0.0, (function (total, group) {
                return total + Core__Option.getOr(group.size, 0.0);
              }));
}

async function assertEditorWideEnough() {
  var width = await measureEditorWidth();
  await resetLayout();
  var required = 220.0 / 0.25;
  if (width >= required) {
    return ;
  }
  throw {
        RE_EXN_ID: "Failure",
        _1: "the editor area is " + width.toString() + "px wide but " + required.toString() + "px is needed for a group to get a quarter of it without falling below VS Code's minimum group width",
        Error: new Error()
      };
}

async function withScenario(position, splitSizingOpt, settingsOpt, body) {
  var splitSizing = splitSizingOpt !== undefined ? splitSizingOpt : "split";
  var settings = settingsOpt !== undefined ? settingsOpt : [];
  var candidate = await Test__Util$AgdaModeVscode.AgdaMode.commandExists("agda");
  var channels = await Test__Util$AgdaModeVscode.activateExtension(candidate);
  var applied = [
      {
        section: "agdaMode",
        key: "view.panelMountPosition",
        value: positionName(position)
      },
      {
        section: "workbench.editor",
        key: "splitSizing",
        value: splitSizing
      }
    ].concat(settings);
  var previous = [];
  for(var index = 0 ,index_finish = applied.length; index < index_finish; ++index){
    var setting = applied[index];
    if (setting !== undefined) {
      var before = await updateGlobalSetting(setting.section, setting.key, setting.value);
      previous.push([
            setting,
            before
          ]);
    }
    
  }
  var failure;
  try {
    await reset(channels);
    await clearWorkbench();
    await assertEditorWideEnough();
    await body(channels);
    failure = undefined;
  }
  catch (raw_exn){
    failure = Caml_js_exceptions.internalToOCamlException(raw_exn);
  }
  var cleanupFailure;
  try {
    await reset(channels);
    cleanupFailure = undefined;
  }
  catch (raw_exn$1){
    cleanupFailure = Caml_js_exceptions.internalToOCamlException(raw_exn$1);
  }
  for(var index$1 = previous.length - 1 | 0; index$1 >= 0; --index$1){
    var match = previous[index$1];
    if (match !== undefined) {
      var setting$1 = match[0];
      await updateGlobalSetting(setting$1.section, setting$1.key, match[1]);
    }
    
  }
  if (failure !== undefined) {
    if (cleanupFailure !== undefined) {
      console.log("[ issue #129 harness: cleanup also failed ]", describeExn(cleanupFailure));
      throw failure;
    }
    throw failure;
  }
  if (cleanupFailure === undefined) {
    return ;
  }
  throw cleanupFailure;
}

async function build(layout) {
  var names = leaves(layout);
  await Vscode.commands.executeCommand("vscode.setEditorLayout", toRawLayout(normalize(layout)));
  for(var index = 0 ,index_finish = names.length; index < index_finish; ++index){
    var name = names[index];
    if (name !== undefined && name !== "Empty") {
      await showInColumn(fileOf(name), index + 1 | 0);
    }
    
  }
}

async function focus(layout, name) {
  var column = leaves(layout).findIndex(function (candidate) {
        return candidate === name;
      }) + 1 | 0;
  return await showInColumn(fileOf(name), column);
}

async function load(channels) {
  Core__Option.forEach(Vscode.window.activeTextEditor, (function (editor) {
          loadedFiles.contents = loadedFiles.contents.concat([editor.document.fileName]);
        }));
  var match = Util$AgdaModeVscode.Promise_.pending();
  var resolve = match[1];
  var stop = Chan$AgdaModeVscode.on(channels.commandHandled, (function (command) {
          if (command === "Load") {
            return resolve();
          }
          
        }));
  var match$1 = await Vscode.commands.executeCommand("agda-mode.load");
  if (match$1 !== undefined) {
    if (match$1.TAG === "Ok") {
      await match[0];
    } else {
      var match$2 = Connection__Error$AgdaModeVscode.toString(match$1._0);
      throw {
            RE_EXN_ID: "Failure",
            _1: match$2[0] + "\n" + match$2[1],
            Error: new Error()
          };
    }
  } else {
    throw {
          RE_EXN_ID: "Failure",
          _1: "agda-mode.load did not return a state",
          Error: new Error()
        };
  }
  return stop();
}

async function loadAndSettle(panelOpensOpt, channels) {
  var panelOpens = panelOpensOpt !== undefined ? panelOpensOpt : true;
  var observer = make();
  var failure;
  try {
    await load(channels);
    await observer.settled(20000, panelOpens);
    failure = undefined;
  }
  catch (raw_exn){
    failure = Caml_js_exceptions.internalToOCamlException(raw_exn);
  }
  observer.stop();
  if (failure !== undefined) {
    throw failure;
  }
  return await capture();
}

async function check(layout, active, position, splitSizingOpt, settingsOpt, shapeOnlyOpt, expected) {
  var splitSizing = splitSizingOpt !== undefined ? splitSizingOpt : "split";
  var settings = settingsOpt !== undefined ? settingsOpt : [];
  var shapeOnly = shapeOnlyOpt !== undefined ? shapeOnlyOpt : false;
  return await withScenario(position, splitSizing, settings, (async function (channels) {
                await build(layout);
                await focus(layout, active);
                var before = await capture();
                Curry._3(Assert.deepStrictEqual, Test__EditorLayout__Util$AgdaModeVscode.show(before.layout), Test__EditorLayout__Util$AgdaModeVscode.show(normalize(layout)), undefined);
                Curry._3(Assert.deepStrictEqual, before.activeGroup, active, undefined);
                var after = await loadAndSettle(undefined, channels);
                return Curry._3(Assert.deepStrictEqual, shapeOnly ? Test__EditorLayout__Util$AgdaModeVscode.showShape(after.layout) : Test__EditorLayout__Util$AgdaModeVscode.show(after.layout), expected, undefined);
              }));
}

var Layout;

var hangGuardMs = 20000;

var minGroupWidth = 220.0;

var smallestSlot = 0.25;

exports.Layout = Layout;
exports.leaves = leaves;
exports.mapLeaves = mapLeaves;
exports.round2 = round2;
exports.normalize = normalize;
exports.flip = flip;
exports.orientationOfInt = orientationOfInt;
exports.intOfOrientation = intOfOrientation;
exports.parseLayout = parseLayout;
exports.toRawGroup = toRawGroup;
exports.toRawLayout = toRawLayout;
exports.snapshotTabGroups = snapshotTabGroups;
exports.nameOfGroup = nameOfGroup;
exports.capture = capture;
exports.Observer = Observer;
exports.hangGuardMs = hangGuardMs;
exports.panelClosed = panelClosed;
exports.stringSetting = stringSetting;
exports.boolSetting = boolSetting;
exports.updateGlobalSetting = updateGlobalSetting;
exports.showInColumn = showInColumn;
exports.describeExn = describeExn;
exports.positionName = positionName;
exports.fileOf = fileOf;
exports.resetLayout = resetLayout;
exports.withHangGuard = withHangGuard;
exports.isDestructionComplete = isDestructionComplete;
exports.loadedFiles = loadedFiles;
exports.quit = quit;
exports.closePanelTabs = closePanelTabs;
exports.reset = reset;
exports.clearWorkbench = clearWorkbench;
exports.minGroupWidth = minGroupWidth;
exports.smallestSlot = smallestSlot;
exports.measureEditorWidth = measureEditorWidth;
exports.assertEditorWideEnough = assertEditorWideEnough;
exports.withScenario = withScenario;
exports.build = build;
exports.focus = focus;
exports.load = load;
exports.loadAndSettle = loadAndSettle;
exports.check = check;
/* updateGlobalSetting Not a pure module */
