// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Js_dict = require("rescript/lib/js/js_dict.js");
var $$Promise = require("reason-promise/lib/js/src/js/promise.bs.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Util$AgdaModeVscode = require("./Util/Util.bs.js");
var State$AgdaModeVscode = require("./State.bs.js");
var Highlighting$AgdaModeVscode = require("./Highlighting.bs.js");

function getState(status) {
  if (status.TAG === /* PendingInit */0) {
    return ;
  } else {
    return status._0;
  }
}

var dict = {};

function get(fileName) {
  return Belt_Option.flatMap(Js_dict.get(dict, fileName), getState);
}

function add(fileName, state) {
  var match = Js_dict.get(dict, fileName);
  if (match !== undefined) {
    if (match.TAG !== /* PendingInit */0) {
      return ;
    }
    Curry._1(match._1, Highlighting$AgdaModeVscode.getSemanticTokens(state.highlighting));
    dict[fileName] = {
      TAG: 1,
      _0: state,
      [Symbol.for("name")]: "Initialized"
    };
    return ;
  }
  dict[fileName] = {
    TAG: 1,
    _0: state,
    [Symbol.for("name")]: "Initialized"
  };
  
}

function remove(fileName) {
  var delete_ = (function (dict, key) {delete dict[key]});
  return delete_(dict, fileName);
}

function removeAndDestroy(fileName) {
  var match = Js_dict.get(dict, fileName);
  if (match === undefined) {
    return $$Promise.resolved(undefined);
  }
  if (match.TAG === /* PendingInit */0) {
    remove(fileName);
    Curry._1(match._1, []);
    return $$Promise.resolved(undefined);
  }
  remove(fileName);
  return State$AgdaModeVscode.destroy(match._0, false);
}

function removeAndDestroyAll(param) {
  return $$Promise.map(Util$AgdaModeVscode.oneByOne(Belt_Array.map(Object.keys(dict), removeAndDestroy)), (function (param) {
                
              }));
}

function isEmpty(param) {
  return Object.keys(dict).length === 0;
}

function requestSemanticTokens(fileName) {
  var match = Js_dict.get(dict, fileName);
  if (match !== undefined) {
    if (match.TAG === /* PendingInit */0) {
      return match._0;
    } else {
      return $$Promise.resolved(Highlighting$AgdaModeVscode.getSemanticTokens(match._0.highlighting));
    }
  }
  var match$1 = $$Promise.pending(undefined);
  var promise = match$1[0];
  dict[fileName] = {
    TAG: 0,
    _0: promise,
    _1: match$1[1],
    [Symbol.for("name")]: "PendingInit"
  };
  return promise;
}

var Module = {
  get: get,
  add: add,
  remove: remove,
  removeAndDestroy: removeAndDestroy,
  removeAndDestroyAll: removeAndDestroyAll,
  isEmpty: isEmpty,
  requestSemanticTokens: requestSemanticTokens
};

exports.Module = Module;
exports.get = get;
exports.add = add;
exports.remove = remove;
exports.removeAndDestroy = removeAndDestroy;
exports.removeAndDestroyAll = removeAndDestroyAll;
exports.isEmpty = isEmpty;
exports.requestSemanticTokens = requestSemanticTokens;
/* Promise Not a pure module */
