// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var State$AgdaModeVscode = require("./State.bs.js");
var Command$AgdaModeVscode = require("./Command.bs.js");
var TaskRunner$AgdaModeVscode = require("./Task/TaskRunner.bs.js");
var Task__Command$AgdaModeVscode = require("./Task/Task__Command.bs.js");

function Impl(Editor) {
  var State = State$AgdaModeVscode.Impl(Editor);
  var dict = { };
  var get = function (fileName) {
    return Js_dict.get(dict, fileName);
  };
  var getByEditor = function (editor) {
    return Belt_Option.flatMap(Curry._1(Editor.getFileName, editor), get);
  };
  var add = function (fileName, state) {
    var match = Js_dict.get(dict, fileName);
    if (match !== undefined) {
      return ;
    } else {
      dict[fileName] = state;
      return ;
    }
  };
  var rename = function (oldName, newName) {
    var delete_ = (function (dict, key) {delete dict[key]});
    return Belt_Option.forEach(Js_dict.get(dict, oldName), (function (state) {
                  console.log("[ states ][ rename ]", oldName, newName);
                  delete_(dict, oldName);
                  return add(newName, state);
                }));
  };
  var remove = function (fileName) {
    var delete_ = (function (dict, key) {delete dict[key]});
    return delete_(dict, fileName);
  };
  var destroy = function (fileName) {
    Belt_Option.forEach(Js_dict.get(dict, fileName), (function (state) {
            console.log("[ states ][ destroy ]");
            Curry._1(State.destroy, state);
            
          }));
    return remove(fileName);
  };
  var contains = function (fileName) {
    return Belt_Option.isSome(Js_dict.get(dict, fileName));
  };
  var destroyAll = function (param) {
    Belt_Array.map(Js_dict.entries(dict), (function (param) {
            return Curry._1(State.destroy, param[1]);
          }));
    
  };
  return {
          State: State,
          dict: dict,
          get: get,
          getByEditor: getByEditor,
          add: add,
          rename: rename,
          remove: remove,
          destroy: destroy,
          contains: contains,
          destroyAll: destroyAll
        };
}

var StateDict = {
  Impl: Impl
};

function Impl$1(Editor) {
  var State = State$AgdaModeVscode.Impl(Editor);
  var dict = { };
  var get = function (fileName) {
    return Js_dict.get(dict, fileName);
  };
  var getByEditor = function (editor) {
    return Belt_Option.flatMap(Curry._1(Editor.getFileName, editor), get);
  };
  var add = function (fileName, state) {
    var match = Js_dict.get(dict, fileName);
    if (match !== undefined) {
      return ;
    } else {
      dict[fileName] = state;
      return ;
    }
  };
  var rename = function (oldName, newName) {
    var delete_ = (function (dict, key) {delete dict[key]});
    return Belt_Option.forEach(Js_dict.get(dict, oldName), (function (state) {
                  console.log("[ states ][ rename ]", oldName, newName);
                  delete_(dict, oldName);
                  return add(newName, state);
                }));
  };
  var remove = function (fileName) {
    var delete_ = (function (dict, key) {delete dict[key]});
    return delete_(dict, fileName);
  };
  var destroy = function (fileName) {
    Belt_Option.forEach(Js_dict.get(dict, fileName), (function (state) {
            console.log("[ states ][ destroy ]");
            Curry._1(State.destroy, state);
            
          }));
    return remove(fileName);
  };
  var contains = function (fileName) {
    return Belt_Option.isSome(Js_dict.get(dict, fileName));
  };
  var destroyAll = function (param) {
    Belt_Array.map(Js_dict.entries(dict), (function (param) {
            return Curry._1(State.destroy, param[1]);
          }));
    
  };
  var States = {
    State: State,
    dict: dict,
    get: get,
    getByEditor: getByEditor,
    add: add,
    rename: rename,
    remove: remove,
    destroy: destroy,
    contains: contains,
    destroyAll: destroyAll
  };
  var State$1 = State$AgdaModeVscode.Impl(Editor);
  var TaskCommand = Task__Command$AgdaModeVscode.Impl(Editor);
  var TaskRunner = TaskRunner$AgdaModeVscode.Impl(Editor);
  var addToSubscriptions = function (f, context) {
    context.subscriptions.push(f);
    
  };
  var activate = function (context) {
    Curry._2(Editor.addToSubscriptions, Curry._1(Editor.onDidCloseEditor, destroy), context);
    Curry._2(Editor.addToSubscriptions, Curry._1(Editor.onDidChangeFileName, (function (oldName, newName) {
                return Belt_Option.forEach(oldName, (function (oldName) {
                              return Belt_Option.forEach(newName, (function (newName) {
                                            if (contains(oldName)) {
                                              if (Curry._1(Editor.isAgda, newName)) {
                                                return rename(oldName, newName);
                                              } else {
                                                return destroy(oldName);
                                              }
                                            }
                                            
                                          }));
                            }));
              })), context);
    Curry._2(Editor.addToSubscriptions, Curry._1(Editor.onDidChangeActivation, (function (prev, next) {
                
              })), context);
    Curry._2(Editor.addToSubscriptions, Curry._2(Editor.registerCommand, "load", (function (editor) {
                return Belt_Option.forEach(Curry._1(Editor.getFileName, editor), (function (fileName) {
                              var _state = get(fileName);
                              if (_state !== undefined) {
                                return ;
                              }
                              var state = Curry._2(State$1.make, context, editor);
                              Curry._2(Editor.addToSubscriptions, Curry._2(State$1.onDestroy, state, (function (param) {
                                          return remove(fileName);
                                        })), context);
                              return add(fileName, state);
                            }));
              })), context);
    Curry._2(Editor.addToSubscriptions, Curry._2(Editor.registerCommand, "quit", (function (editor) {
                return Belt_Option.forEach(Curry._1(Editor.getFileName, editor), (function (fileName) {
                              var _state = get(fileName);
                              if (_state !== undefined) {
                                return destroy(fileName);
                              }
                              
                            }));
              })), context);
    return Belt_Array.forEach(Command$AgdaModeVscode.names, (function (param) {
                  var command = param[0];
                  return Curry._2(Editor.addToSubscriptions, Curry._2(Editor.registerCommand, param[1], (function (editor) {
                                    return Belt_Option.forEach(getByEditor(editor), (function (state) {
                                                  console.log(state);
                                                  Curry._2(TaskRunner.run, state, Curry._1(TaskCommand.dispatch, command));
                                                  
                                                }));
                                  })), context);
                }));
  };
  var deactivate = function (param) {
    return destroyAll(undefined);
  };
  return {
          States: States,
          State: State$1,
          TaskCommand: TaskCommand,
          TaskRunner: TaskRunner,
          addToSubscriptions: addToSubscriptions,
          activate: activate,
          deactivate: deactivate
        };
}

exports.StateDict = StateDict;
exports.Impl = Impl$1;
/* State-AgdaModeVscode Not a pure module */
