// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Nodefs = require("node:fs");

function readdir(filepath) {
  return new Promise((function (resolve, reject) {
                Fs.readdir(filepath, (function (error, files) {
                        if (error == null) {
                          return resolve(files);
                        } else {
                          return reject(error);
                        }
                      }));
              }));
}

async function readFile(filepath) {
  var fileHandle = await Nodefs.promises.open(filepath, "r");
  var buffer = await fileHandle.readFile();
  await fileHandle.close();
  return buffer.toString();
}

exports.readdir = readdir;
exports.readFile = readFile;
/* fs Not a pure module */
