// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Emacs__PlainText(Props) {
  var payload = Props.payload;
  return React.createElement("p", undefined, payload);
}

var make = Emacs__PlainText;

exports.make = make;
/* react Not a pure module */
