resolver: lts-24.1
compiler: ghc-9.10.2
# Allow a newer minor version of GHC than the snapshot specifies
compiler-check: newer-minor

packages: []

extra-deps:
- Agda-2.6.4.3           
- hashable-1.4.7.0@sha256:573f3ab242f75465a0d67ce9d84202650a1606575e6dbd6d31ffcf4767a9a379,6629