name: Spell Checker

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  misc:
    permissions:
      contents: read
      pull-requests: read
    name: spell checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure git safe directory
        run: |
          git config --global --add safe.directory $(pwd)
      - name: check spell
        run: |
          python3 -m venv ./venv
          source ./venv/bin/activate
          pip install codespell
          # exclude files which may be synchronized from other places
          git ls-files | grep -Ev "^asset|package-lock\.json" | xargs -t codespell --ignore-words .github/workflows/ignore_words 2>/dev/null
